// Mock data for ZKFund Dashboard

export const mockFunds = [
  {
    id: 'zkfund_01',
    name: 'Alpha Stealth Fund',
    type: 'Private Equity',
    tvl: 2450000,
    nav: 1.28,
    navChange: 5.2,
    members: 12,
    signers: '3/5',
    status: 'active',
    allocation: [
      { asset: 'ETH', percentage: 45 },
      { asset: 'USDC', percentage: 30 },
      { asset: 'BTC', percentage: 25 },
    ],
  },
  {
    id: 'zkfund_02',
    name: 'Quantum OTC Desk',
    type: 'OTC Trading',
    tvl: 8750000,
    nav: 1.15,
    navChange: 2.8,
    members: 8,
    signers: '4/6',
    status: 'active',
    allocation: [
      { asset: 'USDC', percentage: 60 },
      { asset: 'ETH', percentage: 25 },
      { asset: 'SOL', percentage: 15 },
    ],
  },
  {
    id: 'zkfund_03',
    name: 'Cipher DAO Treasury',
    type: 'DAO Treasury',
    tvl: 15200000,
    nav: 1.42,
    navChange: -1.5,
    members: 156,
    signers: '5/9',
    status: 'active',
    allocation: [
      { asset: 'ETH', percentage: 50 },
      { asset: 'Stables', percentage: 35 },
      { asset: 'Other', percentage: 15 },
    ],
  },
];

export const mockProposals = [
  {
    id: 'prop_001',
    title: 'Allocate 500K USDC to Yield Strategy',
    description: 'Proposal to allocate funds to low-risk yield farming strategies',
    type: 'allocation',
    status: 'active',
    fundId: 'zkfund_01',
    fundName: 'Alpha Stealth Fund',
    requiredSignatures: '3/5',
    currentSignatures: 2,
    deadline: '2024-12-15T23:59:59Z',
    createdAt: '2024-12-08T10:00:00Z',
    createdBy: 'Fund Manager',
    amount: 500000,
  },
  {
    id: 'prop_002',
    title: 'Execute Private Swap: 100 ETH → USDC',
    description: 'Large block trade execution via ZK OTC',
    type: 'swap',
    status: 'pending',
    fundId: 'zkfund_02',
    fundName: 'Quantum OTC Desk',
    requiredSignatures: '4/6',
    currentSignatures: 3,
    deadline: '2024-12-12T18:00:00Z',
    createdAt: '2024-12-09T14:30:00Z',
    createdBy: 'Trader',
    amount: 320000,
  },
  {
    id: 'prop_003',
    title: 'Withdraw 50K to Stealth Address',
    description: 'Private withdrawal for operational expenses',
    type: 'withdraw',
    status: 'executed',
    fundId: 'zkfund_01',
    fundName: 'Alpha Stealth Fund',
    requiredSignatures: '3/5',
    currentSignatures: 5,
    deadline: '2024-12-10T12:00:00Z',
    createdAt: '2024-12-07T09:00:00Z',
    createdBy: 'Board Member',
    amount: 50000,
  },
  {
    id: 'prop_004',
    title: 'Add New Signer to Multisig',
    description: 'Proposal to add new board member as signer',
    type: 'governance',
    status: 'voting',
    fundId: 'zkfund_03',
    fundName: 'Cipher DAO Treasury',
    requiredSignatures: '5/9',
    currentSignatures: 0,
    deadline: '2024-12-20T23:59:59Z',
    createdAt: '2024-12-10T08:00:00Z',
    createdBy: 'Governance Lead',
    votesFor: 89,
    votesAgainst: 34,
    totalVotes: 156,
  },
];

export const mockVotes = [
  {
    id: 'vote_001',
    proposalId: 'prop_004',
    proposalTitle: 'Add New Signer to Multisig',
    fundName: 'Cipher DAO Treasury',
    status: 'active',
    endTime: '2024-12-20T23:59:59Z',
    votesFor: 89,
    votesAgainst: 34,
    abstain: 12,
    totalVotes: 156,
    quorum: 100,
    userVoted: false,
    options: ['Approve', 'Reject', 'Abstain'],
  },
  {
    id: 'vote_002',
    proposalId: 'prop_005',
    proposalTitle: 'Increase Yield Allocation to 40%',
    fundName: 'Alpha Stealth Fund',
    status: 'active',
    endTime: '2024-12-18T23:59:59Z',
    votesFor: 8,
    votesAgainst: 2,
    abstain: 1,
    totalVotes: 12,
    quorum: 7,
    userVoted: true,
    userChoice: 'Approve',
    options: ['Approve', 'Reject', 'Abstain'],
  },
  {
    id: 'vote_003',
    proposalId: 'prop_006',
    proposalTitle: 'Update Fee Structure',
    fundName: 'Quantum OTC Desk',
    status: 'ended',
    endTime: '2024-12-05T23:59:59Z',
    votesFor: 6,
    votesAgainst: 1,
    abstain: 0,
    totalVotes: 8,
    quorum: 5,
    result: 'passed',
    options: ['Approve', 'Reject', 'Abstain'],
  },
];

export const mockTransactions = [
  {
    id: 'tx_001',
    type: 'deposit',
    amount: 100000,
    asset: 'USDC',
    fundName: 'Alpha Stealth Fund',
    status: 'confirmed',
    timestamp: '2024-12-10T15:30:00Z',
    proofHash: '0x8f2e...a3b4',
    from: 'stealth_0x7a3d',
    to: 'zk_pool_01',
  },
  {
    id: 'tx_002',
    type: 'swap',
    amount: 50,
    asset: 'ETH',
    toAsset: 'USDC',
    toAmount: 160000,
    fundName: 'Quantum OTC Desk',
    status: 'confirmed',
    timestamp: '2024-12-10T14:20:00Z',
    proofHash: '0x9c4f...b5d6',
    from: 'zk_pool_02',
    to: 'zk_pool_02',
  },
  {
    id: 'tx_003',
    type: 'withdraw',
    amount: 25000,
    asset: 'USDC',
    fundName: 'Alpha Stealth Fund',
    status: 'pending',
    timestamp: '2024-12-10T12:00:00Z',
    proofHash: '0xa1b2...c3d4',
    from: 'zk_pool_01',
    to: 'stealth_0x8b4c',
    signatures: '2/3',
  },
  {
    id: 'tx_004',
    type: 'allocation',
    amount: 500000,
    asset: 'USDC',
    fundName: 'Cipher DAO Treasury',
    status: 'confirmed',
    timestamp: '2024-12-09T18:45:00Z',
    proofHash: '0xd5e6...f7g8',
    from: 'zk_pool_03',
    to: 'yield_strategy_01',
  },
  {
    id: 'tx_005',
    type: 'deposit',
    amount: 200,
    asset: 'ETH',
    fundName: 'Quantum OTC Desk',
    status: 'confirmed',
    timestamp: '2024-12-09T10:15:00Z',
    proofHash: '0xh9i0...j1k2',
    from: 'stealth_0x9d5e',
    to: 'zk_pool_02',
  },
];

export const mockStats = {
  totalTVL: 26400000,
  totalFunds: 3,
  activeProposals: 4,
  pendingVotes: 2,
  totalMembers: 176,
  weeklyVolume: 1250000,
  zkProofsGenerated: 1847,
  privateTransactions: 342,
};

export const mockActivity = [
  { time: '2 min ago', action: 'New proposal created', fund: 'Alpha Stealth Fund' },
  { time: '15 min ago', action: 'Vote submitted (ZK Proof)', fund: 'Cipher DAO Treasury' },
  { time: '1 hour ago', action: 'Swap executed privately', fund: 'Quantum OTC Desk' },
  { time: '3 hours ago', action: 'New LP deposit', fund: 'Alpha Stealth Fund' },
  { time: '5 hours ago', action: 'Proposal passed', fund: 'Quantum OTC Desk' },
];

export const mockChartData = [
  { date: 'Dec 4', tvl: 24.1, volume: 0.8 },
  { date: 'Dec 5', tvl: 24.5, volume: 1.2 },
  { date: 'Dec 6', tvl: 25.2, volume: 0.9 },
  { date: 'Dec 7', tvl: 25.8, volume: 1.5 },
  { date: 'Dec 8', tvl: 25.5, volume: 1.1 },
  { date: 'Dec 9', tvl: 26.0, volume: 1.3 },
  { date: 'Dec 10', tvl: 26.4, volume: 1.25 },
];
